version: 0.2

phases:
  install:
    runtime-versions: 
      nodejs: 20
    commands:
      - echo Installing Next.js app dependencies...
      - node --version
      - npm install next -g
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  base-directory: out
  files:
    - '**/*'